parameters:
    google_analytics.class: GoogleAnalyticsServerSide\Lib\Tracker

services:
    google_analytics:
        class: %google_analytics.class%
        arguments:    [ %php_ga_accountID% , %php_ga_domain% ]